[package]
name = "activitystreams"
description = "Activity Streams in Rust"
version = "0.5.0-alpha.13"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/Aardwolf/activitystreams"
readme = "README.md"
keywords = ["activitystreams", "activitypub"]
edition = "2018"

[features]
default = ["types"]
derive = ["activitystreams-derive", "serde", "serde_json"]
kinds = ["derive", "serde"]
primitives = ["chrono", "mime", "serde", "thiserror", "url"]
types = ["derive", "kinds", "primitives"]

[dependencies]
activitystreams-derive = { version = "0.5.0-alpha.5", path = "activitystreams-derive", optional = true}
chrono = { version = "0.4", optional = true }
mime = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional = true }
url = { version = "2.1", optional = true }

[dev-dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev.package.activitystreams-derive]
opt-level = 3

[workspace]
members = [
    "activitystreams-derive",
]
