[package]
name = "activitystreams"
description = "Activity Streams in Rust"
version = "0.3.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/Aardwolf/activitystreams"
readme = "README.md"
keywords = ["activitystreams", "activitypub"]
edition = "2018"

[dependencies]
activitystreams-traits = { version = "0.3", path = "activitystreams-traits" }
activitystreams-types = { version = "0.3.0", path = "activitystreams-types" }

[dev-dependencies]
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
activitystreams-derive = { version = "0.3", path = "activitystreams-derive" }

[profile.dev.package.activitystreams-derive]
opt-level = 3

[workspace]
members = [
    "activitystreams-derive",
    "activitystreams-traits",
    "activitystreams-types",
]
