[package]
name = "activitystreams"
description = "Activity Streams in Rust"
version = "0.4.0-alpha.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/Aardwolf/activitystreams"
readme = "README.md"
keywords = ["activitystreams", "activitypub"]
edition = "2018"

[features]
default = ["types"]
derive = ["activitystreams-derive"]
kinds = ["derive", "serde"]
primitives = ["chrono", "mime", "serde", "thiserror", "url"]
types = ["derive", "kinds", "primitives", "serde"]

[dependencies]
activitystreams-derive = { version = "0.4.0-alpha.0", path = "activitystreams-derive", optional = true}
typetag = "0.1.4"
chrono = { version = "0.4", optional = true }
mime = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
thiserror = { version = "1.0", optional = true }
url = { version = "2.1", optional = true }

[dev-dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typetag = "0.1.4"

[profile.dev.package.activitystreams-derive]
opt-level = 3

[workspace]
members = [
    "activitystreams-derive",
]
